apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #这个指mysql要用的东西
  #还要去定义k8s有什么
  name: webook-mysql-pv-claim
spec:
  #可以随便取,不过要和pv中的配置对得上才能找到
  storageClassName: manual
  accessModes:
    #允许多个Pod读写
    - ReadWriteMany
  resources:
    requests:
      #1 GB
      storage: 1Gi
