// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"webookProgram/webook/internal/repository"
	"webookProgram/webook/internal/repository/cache"
	"webookProgram/webook/internal/repository/cache/redis"
	"webookProgram/webook/internal/repository/dao"
	"webookProgram/webook/internal/service"
	"webookProgram/webook/internal/service/sms"
	"webookProgram/webook/internal/service/sms/memory"
	"webookProgram/webook/internal/web"
	"webookProgram/webook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitCache()
	v := ioc.InitMiddlewares(cmdable)
	db := ioc.InitDb()
	userDAO := dao.NewUserDAO(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository)
	codeCache := redis.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := memory.NewService()
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService)
	engine := ioc.InitEngine(v, userHandler)
	return engine
}

// wire.go:

var CodeCacheSet = wire.NewSet(redis.NewCodeCache, wire.Bind(new(cache.CodeCache), new(*redis.CodeRedisCache)))

var SmsServiceSet = wire.NewSet(memory.NewService, wire.Bind(new(sms.Service), new(*memory.Service)))
