// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"webookProgram/webook/internal/repository"
	"webookProgram/webook/internal/repository/cache"
	"webookProgram/webook/internal/repository/cache/redis"
	"webookProgram/webook/internal/repository/dao"
	"webookProgram/webook/internal/service"
	"webookProgram/webook/internal/service/sms"
	"webookProgram/webook/internal/service/sms/memory"
	"webookProgram/webook/internal/web"
	"webookProgram/webook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := InitCache()
	limiter := ioc.InitSlideWindowLimit(cmdable)
	handler := ioc.NewRedisJwtHandler(cmdable)
	v := ioc.InitMiddlewares(limiter, handler)
	gormDB := InitTestDb()
	userDAO := dao.NewUserDAO(gormDB)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	loggerV1 := InitLogger()
	userService := service.NewUserService(userRepository, loggerV1)
	codeCache := redis.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := ioc.InitSMSService(limiter)
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, handler)
	oauth2Service := ioc.InitOAuth2WechatService()
	wechatHandlerConfig := ioc.NewWechatHandlerConfig()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(userService, oauth2Service, wechatHandlerConfig, handler)
	articleDAO := dao.NewArticleDAO(gormDB)
	articleRepository := repository.NewArticleRepository(articleDAO)
	articleService := service.NewArticleService(articleRepository)
	articleHandler := web.NewArticleHandler(articleService, loggerV1)
	engine := ioc.InitEngine(v, userHandler, oAuth2WechatHandler, articleHandler)
	return engine
}

func InitArticleHandler() *web.ArticleHandler {
	gormDB := InitTestDb()
	articleDAO := dao.NewArticleDAO(gormDB)
	articleRepository := repository.NewArticleRepository(articleDAO)
	articleService := service.NewArticleService(articleRepository)
	loggerV1 := InitLogger()
	articleHandler := web.NewArticleHandler(articleService, loggerV1)
	return articleHandler
}

// wire.go:

var thirdProvider = wire.NewSet(InitTestDb, InitCache, InitLogger)

var CodeCacheSet = wire.NewSet(redis.NewCodeCache, wire.Bind(new(cache.CodeCache), new(*redis.CodeRedisCache)))

var SmsServiceSet = wire.NewSet(memory.NewService, wire.Bind(new(sms.Service), new(*memory.Service)))
